#!/bin/sh

nl='
'
: ${XDG_DATA_HOME:="$HOME/.local/share"}
store="$XDG_DATA_HOME/git-credential-gpg"

getquery () {
  host=
  user=
  pass=
  while IFS="$nl" read line; do
    [ -n "$line" ] || break
    case "$line" in
      protocol=*|host=*|path=*) host="$host$line$nl" ;;
      username=*) user="$user$line$nl" ;;
      password=*) pass="$pass$line$nl" ;;
    esac
  done
  input="$host$user$pass"
  hash1=$(printf %s "$host$user" | sort | sha1sum | cut -f1 -d' ')
  hash2=$(printf %s "$host" | sort | sha1sum | cut -f1 -d' ')
}

case "$2" in
  get)
    getquery
    [ -r "$store/$hash1" ] || exit
    gpg --batch -q -d "$store/$hash1"
    ;;
  store)
    getquery
    [ -d "$store" ] || mkdir -m 700 -p "$store"
    umask 0077
    printf %s "$input" | gpg --batch --yes -q -a -e -r "$1" -o "$store/$hash1"
    cp "$store/$hash1" "$store/$hash2"
    ;;
  erase)
    getquery
    rm -f "$store/$hash1" "$store/$hash2"
    ;;
  *)
    printf "usage: git-credential-gpg <gpg-key> <get|store|erase>\n" 1>&2
    exit 1
    ;;
esac
